### ISSUE TITLE
List technos relative to functionalities to deploy

### ISSUE THREAD

**Issue by Agadagluglu** [Agadagluglu/polfran#1]
Technologies potentielles :
 
- Firewall : netfilter (iptables), palo alto, f5, checkpoint, juniper, cisco
- Proxy : Squid, Bluecoat, zscaler, nginx, juniper, ironport, f5
- VPN : openvpn, juniper, cisco, palo alto
- IPBX : asterisk, cisco
- File sharing : owncloud, openstack, nass, cifs, smb, samba, nfs, swift, S3
- Supp : nagios, scom, centreon, shrinken, sabix
- Metro : cacti, librenms, ntop, eyes of network
- Logs : splunk, ELK, syslog

**Comment by Agadagluglu** [comment]
Pour les firewalls > plusieurs firewall de marques différentes/technos différentes.
Penser aux VMs pour la virtualisation de l'infra.

**Comment by Agadagluglu** [comment]
Technologies potentielles :
 
- Firewall : netfilter (iptables), paloalto, f5, ...
- Proxy : Squid, Bluecoat, zscaler, nginx, juniper, ironport, f5
- VPN : openvpn, juniper
- IPBX : asterisk, cisco
- File sharing : owncloud, openstack, nass
- Supp : nagios, scom, centreon, shrinken, sabix
- Metro : cacti, librenms, ntop
- Logs : splunk, ELK, syslog

**Comment by fbouynot** [comment]
VPN : +cisco & palo alto

**Comment by fbouynot** [comment]
Firewall : + checkpoint, juniper, cisco

**Comment by fbouynot** [comment]
partage de fichier : +cifs, smb, samba, nfs, swift, S3

**Comment by fbouynot** [comment]
supervision / metrologie : + eyes of network

**Comment by Agadagluglu** [comment]
C'est rajouté. D'autres idées ?

**Comment by fbouynot** [comment]
Comparatif firewall entreprise : le questions à se poser, les solutions à envisager.
http://www.tomshardware.fr/articles/firewall-pare-feu-securite,2-2362.html

**Comment by fbouynot** [comment]
Sous-catégories créées.
