### ISSUE TITLE
Reseau

### ISSUE THREAD

**Issue by Agadagluglu** [Agadagluglu/polfran#3]
Requirements : 

- Routage et communication sous GNS3
- Liaison VPN ipsec entre sites
- Switiching en vlans (ipbix/pc/etc)
- Deux niveau de firewall
- Redondance de firewall
- Routage possible avec les firewalls

**Comment by fbouynot** [comment]
A diviser en sous parties et fermer.

**Comment by fbouynot** [comment]
Catégories créées.
