### ISSUE TITLE
KVM disponible sur le serveur remote

### ISSUE THREAD

**Issue by Agadagluglu** [Agadagluglu/polfran#7]
Mettre en place l'infrastructure de virtualisation sur la bête.

"Hyperviseur" KVM à mettre en place.

**Comment by Agadagluglu** [comment]
Créer les comptes pour les membres du groupes.

**Comment by fbouynot** [comment]
Définir un groupe et lui attribuer les droits, ajouter les membres dans le groupe

**Comment by Agadagluglu** [comment]
+1

Y'a plus qu'a...

**Comment by fbouynot** [comment]
Utilisateurs et groupes créés et droits ajoutés.
